### PR TITLE
update package versions in readme

### PR DESCRIPTION
**Pull request by jneira**

### CODE REVIEW

**Comment by jneira** [comment]
@rahulmutt is to show only the last version this the correct way?

**Comment by rahulmutt** [comment]
You should show a version range, similar to how it's done in https://github.com/typelead/eta-hackage

**Comment by jneira** [comment]
@rahulmutt i've updated the versions with ranges

**Comment by rahulmutt** [comment]
@jneira Thanks a lot for the updates!

**Pull request merged**
